[build]
  publish = "dist"
  command = "npm run build"
        body {
            background-color: hsl(var(--background));
            color: hsl(var(--foreground));
            font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }
[functions]
  directory = "dist"
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 20px;
        }
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
        header {
            background: linear-gradient(135deg, hsl(var(--primary)), hsl(142, 60%, 45%));
            color: white;
            padding: 2rem 0;
            text-align: center;
        }
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
